[package]
name = "control-surface"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3.10"
embedded-hal = { version = "1.0", features = ["defmt-03"] }
embedded-hal-async = { version = "1", features = ["defmt-03"] }
heapless = "0.8.0"
